version: "3"

services: 
  app:
    build:
      context: node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh node index.js
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
    tty: true
    ports: 
      - "3000:3000"
    depends_on: 
      - db

  nginx:
    restart: always
    container_name: nginx
    build:
        context: ./nginx
    ports:
        - "8080:80"
    networks:
      - node-network
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always #se cair restarta
    tty: true #ativar entrada via terminal
    volumes: 
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    networks:
      - node-network

networks:
  node-network:
    driver: bridge